config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :plans
  mount Sidekiq::Web => '/sidekiq'
  devise_for :employees
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  mount ActionCable.server => '/cable'
  resources :employees, :except => [:index]
  get '/assign/employees', to: "employees#listing"
  resources :templates, :except => [:show, :index]
  resources :userhome, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :orders, :except => [:index]
  resources :attachments, :only => [:create]
  get '/admin/orders', to: 'home#admin_orders'
  get '/admin/managers', to: 'home#admin_managers'
  get '/admin/templates', to: 'home#admin_templates'
  get '/admin/clients', to: 'home#admin_clients'
  get '/managers/dashboard', to: 'home#manager_dashboard'
  get '/clients/dashboard', to: 'home#client_dashboard'
  get '/admin/dashboard', to: 'home#admin_dashboard'
  root 'home#index'
  get '/terms', to: 'home#terms'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/notifications', to: 'home#notifications'
  post 'subscription_checkout' => 'plans#subscription_checkout'
  get 'invoices' => 'plans#invoices'
  put 'cancel_subscription' => 'plans#cancel_subscription'
  get 'show_invoice' => 'plans#show_invoice'
  
  get 'unsub_user',to: 'home#unsub_user'
  post 'stripe_payment_succeeded' => 'plans#webhook_payment_succeeded'
  post 'stripe_payment_failure' => 'plans#webhook_payment_failure'
  # scope '/admin' do
    resources :chats, except: [:edit,:new]
    resources :messages
  # end
  match "*path", to: "home#error", via: :all
end

app/models/notification.rb
class Notification < ApplicationRecord
    enum status:[:created,:deleted,:updated,:modification,:completed,:delivered,:reviewed,:assign_order,:ready_for_review]
    belongs_to :notify, polymorphic: true
    belongs_to :recipient, polymorphic: true
    belongs_to :actor, polymorphic: true
    
    after_create_commit :notification_job
    
    def notification_job
        NotificationJob.perform_later(self)
        EmployeeMailer.notification_email(self).deliver_later
    end
end

app/views/notifications/_notification.html.erb
<% text = nil %>
<% if notification.notify_type=='Order' and notification.created? %>
    <% text = "#{notification.notify_type} is created by #{notification.actor.name}" %>
<% elsif notification.notify_type=='Order' and notification.assign_order? %>
    <% text = "#{notification.actor.name} has assigned you order" %>
<% elsif notification.notify_type=='Order' and notification.delivered? %>
    <% text = "#{notification.actor.name} has delivered a order" %>
<% elsif notification.notify_type=='Order' and notification.ready_for_review? %>
    <% text = "#{notification.actor.name} has delivered your order and ready for review" %>
<% elsif notification.notify_type=='Order' and notification.completed? and notification.recipient.admin? %>
    <% text = "The delivered order by #{notification.notify.employee.name} has accepted by #{notification.actor.name}" %>
<% elsif notification.notify_type=='Order' and notification.completed? and notification.recipient.manager? %>
    <% text = "#{notification.actor.name} has accepted and rated the delivered order" %>
<% elsif notification.notify_type=='Order' and notification.modification? and notification.recipient.admin? %>
    <% text = "#{notification.actor.name} has requested modification from #{notification.notify.employee.name} for the order" %>
<% elsif notification.notify_type=='Order' and notification.modification? and notification.recipient.manager? %>
    <% text = "#{notification.actor.name} has requested modification for the order" %>
<% elsif notification.notify_type=='Message' and notification.created? %>
    <% text = "You have recieved a new message from #{notification.actor.name}" %>
<% end %>
<% pathh = order_path(notification.notify) if notification.notify_type == 'Order'  %>
<% pathh = chat_path(notification.notify.chat) if notification.notify_type == 'Message'  %>
<div class="notifications alert alert-info">
      <a href="<%= pathh %>"><%= text %></a>
</div>