config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :plans
  mount Sidekiq::Web => '/sidekiq'
  devise_for :employees
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  mount ActionCable.server => '/cable'
  resources :employees, :except => [:index]
  get '/assign/employees', to: "employees#listing"
  resources :templates, :except => [:show, :index]
  resources :userhome, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :orders, :except => [:index]
  resources :attachments, :only => [:create]
  get '/admin/orders', to: 'home#admin_orders'
  get '/admin/managers', to: 'home#admin_managers'
  get '/admin/templates', to: 'home#admin_templates'
  get '/admin/clients', to: 'home#admin_clients'
  get '/managers/dashboard', to: 'home#manager_dashboard'
  get '/clients/dashboard', to: 'home#client_dashboard'
  get '/admin/dashboard', to: 'home#admin_dashboard'
  root 'home#index'
  get '/terms', to: 'home#terms'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/notifications', to: 'home#notifications'
  post 'subscription_checkout' => 'plans#subscription_checkout'
  get 'invoices' => 'plans#invoices'
  put 'cancel_subscription' => 'plans#cancel_subscription'
  get 'show_invoice' => 'plans#show_invoice'
  
  get 'unsub_user',to: 'home#unsub_user'
  post 'stripe_payment_succeeded' => 'plans#webhook_payment_succeeded'
  post 'stripe_payment_failure' => 'plans#webhook_payment_failure'
  # scope '/admin' do
    resources :chats, except: [:edit,:new]
    resources :messages
  # end
  match "*path", to: "home#error", via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, only:[:client_dashboard]
    before_action :authenticate_employee!, only:[:manager_dashboard, :admin_dashboard]
    authorize_resource :class => false, except: [:privacy_policy,:terms,:unsub_user]
    
    def index
        @stripe_list = Stripe::Plan.all
        @plans = @stripe_list[:data]
    end
    
    def admin_orders
        @pending_orders = Order.where(:status => "pending")
        @assigned_orders = Order.where(:status => "assigned")
        @delivered_orders = Order.where(:status => "delivered")
        @complete_orders = Order.where(:status => "complete")
    end
    
    def admin_managers
        @managers = Employee.where(:role => "manager")
    end
    
    def admin_templates
        @templates = Template.all
    end
    
    def admin_clients
        @clients = User.all
    end
    
    def admin_dashboard
        @pending_orders = Order.where(:status => "pending")
        # @delivered_orders = []
    end
    
    def manager_dashboard
        @orders = current_employee.orders
        @pending_orders = @orders.assigned + @orders.in_revision
        @delivered_orders = @orders.delivered
        @complete_orders = @orders.complete
    end
    def notifications
        user = current_employee || current_user
        @notifications = user.notifications.order('created_at DESC')
    end
    
    def client_dashboard
        if @signed_in_user.subscribe?
            @orders = current_user.orders
            @pending_orders = current_user.orders.pending + current_user.orders.in_revision
            @assigned_orders = current_user.orders.assigned
            @delivered_orders = current_user.orders.delivered
            @complete_orders = current_user.orders.complete
        else
            @stripe_list = Stripe::Plan.all
            @plans = @stripe_list[:data]
            render 'unsub_user'
        end
    end
    
    def unsub_user
    end
    
    def 
    
    def error
    end
    def privacy_policy
    end
    def terms
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_client_dashboard.html.erb
<div class="main-div">
 <div id="wrapper">
    <%= render 'layouts/sidebar' %>
orders
<%= link_to 'place order', new_order_path %>
<% if @orders.present? %>
    <div class="row">
        <div class="col-md-6">
            your pending orders
            <table>
                <tr>
                    <th>No.</th>
                    <th>Status</th>
                    <th>amount</th>
                    <th>deadline</th>
                </tr>
                <% @pending_orders.each do |o| %>
                    <tr>
                        <td><%= o.id %></td>
                        <td><%= o.status %></td>
                        <td><%= o.amount %></td>
                        <td><%= o.duration %></td>
                        <td><%= link_to "edit", edit_order_path(o) %></td>
                        <td><%= link_to "delete",order_path(o), :method => :delete %></td>
                    </tr>
                <% end %>
            </table>
        </div>
        <div class="col-md-6">
            your complete orders
            <table>
                <tr>
                    <th>No.</th>
                    <th>status</th>
                    <th colspan="2">Files</th>
                </tr>
                <% @complete_orders.each do |o| %>
                    <tr>
                        <td><%= o.id %></td>
                        <td><%= o.status %></td>
                        <% if Attachment.where(:order_id => o.id).first.image.present? %>
                            <td><%= link_to "image", Attachment.where(:order_id => o.id).first.image.url %></td>
                        <% end %>
                        <% if Attachment.where(:order_id => o.id).first.pdf.present? %>
                            <td><%= link_to "pdf", Attachment.where(:order_id => o.id).first.pdf.url %></td>
                        <% end %>
                        <td><%= link_to "accept", order_path(o, :order => {:status => "accepted", :template_id => o.template_id}), :method => :put %></td>
                        <td><%= link_to "revise", order_path(o, :order => {:status => "in_revision", :template_id => o.template_id}), :method => :put %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <center>accepted orders</center>
            <table>
                <tr>
                    <th>No.</th>
                    <th>Status</th>
                    <th>amount</th>
                    <th>deadline</th>
                </tr>
                <% @accepted_orders.each do |o| %>
                    <tr>
                        <td><%= o.id %></td>
                        <td><%= o.status %></td>
                        <td><%= o.amount %></td>
                        <td><%= o.duration %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
<% else %>
    <h4>no orders yet</h4>
<% end %>
<div class="footer">
        <div class="pull-right">
            Developed by <a href="http://www.systemplus.com.pk/" target="_blank">System Plus</a>
        </div>
        <div>
            <strong>Copyright</strong> Design360 &copy; 2018
        </div>
    </div>
    </div>
    
</div>
</div>

app/views/home/_manager_dashboard.html.erb
<div class="main-div">
 <div id="wrapper">
    <%= render 'layouts/sidebar' %>
<% if @orders.present? %>
    your orders
    <table>
        <tr>
            <th>No.</th>
            <th>Status</th>
            <th>amount</th>
            <th>deadline </th>
        </tr>
        <% @orders.each do |o| %>
            <tr>
                <td><%= o.id %></td>
                <td><%= o.status %></td>
                <td><%= o.amount %></td>
                <td>
                    <%= o.duration %> days from <%= o.created_at %>
                </td>
                <td><%= link_to "complete", new_order_attachment_path(o) %></td>
            </tr>
        <% end %>
    </table>
<% else %>
    <h4>no orders yet</h4>
<% end %>
<div class="footer">
        <div class="pull-right">
            Developed by <a href="http://www.systemplus.com.pk/" target="_blank">System Plus</a>
        </div>
        <div>
            <strong>Copyright</strong> Design360 &copy; 2018
        </div>
    </div>
    </div>
    
</div>
</div>

app/views/home/admin_managers.html.erb
<div class="main-div">
 <div id="wrapper">
    <%= render 'layouts/sidebar' %>
    <div class="row wrapper border-bottom white-bg page-heading" id="Managers">
        <div class="col-lg-10">
            <h2>Managers</h2>
        </div>
        <div class="col-lg-2">
            <%= link_to 'Add Manager', new_employee_path, class:"btn btn-primary", style:"margin-top:15px;" %>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>All Managers</h5>
                    
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>

        
                    </div>
                </div>
                <div class="ibox-content">

                <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <% @managers.each do |mag| %>
                <tr>
                    <td><%= mag.name %></td>
                    <td><%= mag.email %></td>
                    <td><%= link_to 'Edit', edit_employee_path(mag) %></td>
                    <td><%= link_to 'Delete', employee_path(mag), :method => :delete %></td>
                </tr>
                <% end %>
                </tbody>
                
                </table>
                    </div>

                </div>
            </div>
        </div>
        </div>
    </div>
<%= render 'layouts/footer' %>
</div>
</div>

app/views/home/client_dashboard.html.erb
<div class="main-div">
 <div id="wrapper">
<% user = current_employee || current_user %>
<%= render partial: 'layouts/sidebar', locals:{notifications: user.notifications} %>

<% if @orders.present? %>
<div class="row wrapper border-bottom white-bg page-heading">
        
    <% if can? :create, Order %>
    <%#= current_user.orders.where.not(status:"complete").count < current_user.plan.order_count%>
    <!--not (@orders.pending.present? or @orders.assigned.present? or @orders.delivered.present? or @orders.in_revision.present?) %>-->
        <div class="col-lg-10">
            <h2>Orders</h2>
        </div>
        <div class="col-lg-2">
            <%= link_to 'Place Order', new_order_path, class:"btn btn-primary", style:"margin-top:15px;" %>
        </div>
    <% else %>
        <div class="col-lg-8">
            <h2>Orders</h2>
        </div>
        <div class="col-lg-4" style="margin-top:15px;">
            <p class="btn btn-primary" disabled>You have on-going orders. You cannot add new ones.</p>
        </div>
    <% end %>
</div>



  <ul class="nav nav-tabs">
    <li class="nav-item active">
      <a class="nav-link" href="#pending_orders" role="tab" data-toggle="tab">Pending</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#assigned_orders" role="tab" data-toggle="tab">Assigned</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#delivered_orders" role="tab" data-toggle="tab">Delivered</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#complete_orders" role="tab" data-toggle="tab">Complete</a>
    </li>
  </ul>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="pending_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Pending Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Status</th>
                        <th>Actions</th>
                        <th>Actions</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @pending_orders.each do |o| %>
                    <tr>
                        <td><%= o.status %></td>
                        <td><%= link_to "Edit", edit_order_path(o) %></td>
                        <td><%= link_to "Delete",order_path(o), :method => :delete %></td>
                        <td><%= link_to "Show", order_path(o) %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane fade in" id="assigned_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Assigned Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Manager</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @assigned_orders.each do |o| %>
                    <tr>
                        <td><%= o.employee_order.employee.name %></td>
                        <td><%= link_to "Show", order_path(o) %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane fade in" id="delivered_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Delivered Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Manager</th>
                        <th>Comments</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @delivered_orders.each do |o| %>
                    <tr>
                        <td><%= o.employee.name %></td>
                        <td><%= o.review %></td>
                        <td><%= link_to "Show", order_path(o) %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>

    </div>
    <div role="tabpanel" class="tab-pane fade in" id="complete_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Complete Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Manager</th>
                        <th>Rating</th>
                        <th>Review</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @complete_orders.each do |o| %>
                    <tr>
                        <td><%= o.employee.name %></td>
                        <td><%= o.rating %></td>
                        <td><%= o.review %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>

    </div>
</div>
<% else %>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>No Orders Yet</h2>
    </div>
    <div class="col-lg-2">
         <%= link_to 'Place Order', new_order_path, class:"btn btn-primary", style:"margin-top:15px;" %>
    </div>
</div>
<% end %>

<%= render 'layouts/footer' %>
</div>
</div>

app/views/home/error.html.erb
    <div class="middle-box text-center animated fadeInDown">
        <h1>404</h1>
        <h3 class="font-bold">Page Not Found</h3>

        <div class="error-desc">
            Sorry, but the page you are looking for has note been found. Try checking the URL for error, then hit the refresh button on your browser or go to the <a href="/">Home Page<a>.
            
        </div>
    </div>

app/views/home/manager_dashboard.html.erb
<div class="main-div">
 <div id="wrapper">
<%= render 'layouts/sidebar' %>

<% if @orders.present? %>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Orders</h2>
    </div>
</div>

<ul class="nav nav-tabs">
    <li class="nav-item active">
      <a class="nav-link" href="#pending_orders" role="tab" data-toggle="tab">Pending</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#delivered_orders" role="tab" data-toggle="tab">Delivered</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#complete_orders" role="tab" data-toggle="tab">Complete</a>
    </li>
  </ul>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="pending_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Pending Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Client</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @pending_orders.each do |o| %>
                    <tr>
                        <td><%= o.user.name %></td>
                        <td><%= link_to "Edit", edit_order_path(o) %></td>
                        <td><%= link_to "Delete",order_path(o), :method => :delete %></td>
                        <td><%= link_to "Show", order_path(o) %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane fade in" id="delivered_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Delivered Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Client</th>
                        <th>Comments</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @delivered_orders.each do |o| %>
                    <tr>
                        <td><%= o.user.name %></td>
                        <td><%= o.review %></td>
                        <td><%= link_to "Show", order_path(o) %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>

    </div>
    <div role="tabpanel" class="tab-pane fade in" id="complete_orders">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Complete Orders</h5>
                        
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
        
                    <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example managers" >
                    <thead>
                    <tr>
                        <th>Client</th>
                        <th>Rating</th>
                        <th>Review</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @complete_orders.each do |o| %>
                    <tr>
                        <td><%= o.user.name %></td>
                        <td><%= o.rating %></td>
                        <td><%= o.review %></td>
                    </tr>
                    <% end %>
                    </tbody>
                    
                    </table>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        </div>

    </div>
</div>

<% else %>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>No Orders Yet</h2>
    </div>
</div>
<% end %>

<%= render 'layouts/footer' %>
</div>
</div>

app/views/home/old_admin_dashboard.html.erb
<div class="row">
    <div class="col-md-6">
        <center>managers</center>
        <%= link_to 'add manager', new_employee_path %>
        <table>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
            </tr>
            <% @managers.each do |mag| %>
                <tr>
                    <td><%= mag.name %></td>
                    <td><%= mag.email %></td>
                    <td>to be determined</td>
                    <td><%= link_to 'edit', edit_employee_path(mag) %></td>
                    <td><%= link_to 'delete', employee_path(mag), :method => :delete %></td>
                </tr>
            <% end %>
        </table>
    </div>
    <div class="col-md-6">
        <center>pending orders</center>
        <table>
            <tr>
                <th>client</th>
                <th>amount</th>
                <th>duration</th>
            </tr>
            <% @pending_orders.each do |ord| %>
                <tr>
                    <td><%= User.find(ord.user_id).name %></td>
                    <td><%= ord.amount %></td>
                    <td><%= ord.duration %></td>
                    <td><%= link_to "assign", employees_path(ord) %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <center>Templates</center>
        <%= link_to 'add template', new_template_path %>
        <br>
        <% @templates.each do |tem| %>
            <%= tem.name %>
            <img src=<%= tem.image.url %> alt="<%= tem.name %>" height='50px' width='50px'>
            <%= link_to 'delete', template_path(tem), :method => :delete %> 
            <br>
        <% end %>
    </div>
    <div class="col-md-6">
        <center>assigned orders</center>
        <table>
            <tr>
                <th>client</th>
                <th>manager</th>
                <th>status</th>
            </tr>
            <% @employee_orders.each do |ord| %>
                <tr>
                    <td><%= User.find(Order.find(ord.order_id).user_id).name %></td>
                    <td><%= Employee.find(ord.employee_id).name %></td>
                    <td><%= Order.find(ord.order_id).status %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/home/old_client_dashboard.html.erb
orders
<%= link_to 'place order', new_order_path %>
<% if @orders.present? %>
    <div class="row">
        <div class="col-md-6">
            your pending orders
            <table>
                <tr>
                    <th>No.</th>
                    <th>Status</th>
                    <th>amount</th>
                    <th>deadline</th>
                </tr>
                <% @pending_orders.each do |o| %>
                    <tr>
                        <td><%= o.id %></td>
                        <td><%= o.status %></td>
                        <td><%= o.amount %></td>
                        <td><%= o.duration %></td>
                        <td><%= link_to "edit", edit_order_path(o) %></td>
                        <td><%= link_to "delete",order_path(o), :method => :delete %></td>
                    </tr>
                <% end %>
            </table>
        </div>
        <div class="col-md-6">
            your complete orders
            <table>
                <tr>
                    <th>No.</th>
                    <th>status</th>
                    <th colspan="2">Files</th>
                </tr>
                <% @complete_orders.each do |o| %>
                    <tr>
                        <td><%= o.id %></td>
                        <td><%= o.status %></td>
                        <% if Attachment.where(:order_id => o.id).first.image.present? %>
                            <td><%= link_to "image", Attachment.where(:order_id => o.id).first.image.url %></td>
                        <% end %>
                        <% if Attachment.where(:order_id => o.id).first.pdf.present? %>
                            <td><%= link_to "pdf", Attachment.where(:order_id => o.id).first.pdf.url %></td>
                        <% end %>
                        <td><%= link_to "accept", order_path(o, :order => {:status => "accepted", :template_id => o.template_id}), :method => :put %></td>
                        <td><%= link_to "revise", order_path(o, :order => {:status => "in_revision", :template_id => o.template_id}), :method => :put %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <center>accepted orders</center>
            <table>
                <tr>
                    <th>No.</th>
                    <th>Status</th>
                    <th>amount</th>
                    <th>deadline</th>
                </tr>
                <% @accepted_orders.each do |o| %>
                    <tr>
                        <td><%= o.id %></td>
                        <td><%= o.status %></td>
                        <td><%= o.amount %></td>
                        <td><%= o.duration %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
<% else %>
    <h4>no orders yet</h4>
<% end %>

app/views/home/old_manager_dashboard.html.erb
<div class="main-div">
 <div id="wrapper">
    <%= render 'layouts/sidebar' %>
<% if @orders.present? %>
    your orders
    <table>
        <tr>
            <th>No.</th>
            <th>Status</th>
            <th>amount</th>
            <th>deadline </th>
        </tr>
        <% @orders.each do |o| %>
            <tr>
                <td><%= o.id %></td>
                <td><%= o.status %></td>
                <td><%= o.amount %></td>
                <td>
                    <%= o.duration %> days from <%= o.created_at %>
                </td>
                <td><%= link_to "Complete", new_order_attachment_path(o) %></td>
            </tr>
        <% end %>
    </table>
<% else %>
    <h4>no orders yet</h4>
<% end %>
<%= render 'layouts/footer' %>
</div>
</div>