config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :plans
  mount Sidekiq::Web => '/sidekiq'
  devise_for :employees
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  mount ActionCable.server => '/cable'
  resources :employees, :except => [:index]
  get '/assign/employees', to: "employees#listing"
  resources :templates, :except => [:show, :index]
  resources :userhome, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :orders, :except => [:index]
  resources :attachments, :only => [:create]
  get '/admin/orders', to: 'home#admin_orders'
  get '/admin/managers', to: 'home#admin_managers'
  get '/admin/templates', to: 'home#admin_templates'
  get '/admin/clients', to: 'home#admin_clients'
  get '/managers/dashboard', to: 'home#manager_dashboard'
  get '/clients/dashboard', to: 'home#client_dashboard'
  get '/admin/dashboard', to: 'home#admin_dashboard'
  root 'home#index'
  get '/terms', to: 'home#terms'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/notifications', to: 'home#notifications'
  post 'subscription_checkout' => 'plans#subscription_checkout'
  get 'invoices' => 'plans#invoices'
  put 'cancel_subscription' => 'plans#cancel_subscription'
  get 'show_invoice' => 'plans#show_invoice'
  
  get 'unsub_user',to: 'home#unsub_user'
  post 'stripe_payment_succeeded' => 'plans#webhook_payment_succeeded'
  post 'stripe_payment_failure' => 'plans#webhook_payment_failure'
  # scope '/admin' do
    resources :chats, except: [:edit,:new]
    resources :messages
  # end
  match "*path", to: "home#error", via: :all
end

app/models/plan.rb
class Plan < ApplicationRecord
    serialize :stripe_response, JSON
    has_many :plan_subscribers,dependent: :destroy
    
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:subscription_checkout,:cancel_subscription,:invoices]
  skip_before_action  :verify_authenticity_token,only: [:webhook_payment_succeeded,:webhook_payment_failure]
  # after_action :redirect_func,only: [:webhook_payment_succeeded,:webhook_payment_failure]

  require 'stripe'
  
  def subscription_checkout
    plan_id = params[:stripe_plan_id]
    @plan = Plan.all.select{|p| p.stripe_response["id"] == plan_id }.first
    plan = Stripe::Plan.retrieve(plan_id)
    #This should be created on signup.
    if @signed_in_user.stripe_response.present?
      customer = Stripe::Customer.retrieve(@signed_in_user.stripe_response["id"])
    else
    
      customer = Stripe::Customer.create(
              :description => "Customer for #{@signed_in_user.email}",
              :source => params[:stripeToken],
              :email => params[:stripeEmail]
            )
      @signed_in_user.update(stripe_response: customer)
    end
    
    # Save this in your DB and associate with the user;s email
    stripe_subscription = customer.subscriptions.create(:plan => plan.id)
    PlanSubscriber.first_or_create(plan_id: @plan.id, user_id: @signed_in_user.id).update!(stripe_response: stripe_subscription)
    
    @signed_in_user.subscribe!
    redirect_to clients_dashboard_path,notice: "You have successfully subscribed to Design360 #{@plan.name} Plan"
  end
  
  def cancel_subscription
    stripe_sub_id = @signed_in_user.plan_subscriber.stripe_response["id"]
    Stripe::Subscription.retrieve(stripe_sub_id).delete
    @signed_in_user.plan_subscriber.update(stripe_response: Stripe::Subscription.retrieve(stripe_sub_id))
    @signed_in_user.cancelled!
    @signed_in_user.delete_stripe_customer
    redirect_to clients_dashboard_path, notice: "Subscription cancelled"
  end
  
  def invoices
    if @signed_in_user.stripe_response.present?
      @invoices = @signed_in_user.invoice
    end
  end
  
  def show_invoice
    @invoice = Stripe::Invoice.retrieve(id: params[:stripe_invoice_id])
    respond_to do |format|
      format.js
    end
  end
  
  def webhook_payment_succeeded
    # byebug
    @signed_in_user = User.select{ |user| user.stripe_response and user.stripe_response["id"] == params[:data][:object][:customer] }.first
    @signed_in_user.subscribe!

  end
  
  def webhook_payment_failure
    @signed_in_user = User.select{ |user| user.stripe_response and user.stripe_response["id"] == params[:data][:object][:customer] }.first
    @signed_in_user.cancelled!
  end

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    # byebug
    # plan_params[:trial_period]  = nil if plan_params[:trial_period]==""
    price =  plan_params[:trial_period]=="" ? nil : plan_params[:trial_period]
    subscription = Stripe::Plan.create(
      :product => {
        :name => plan_params[:name],
      },
      :amount => (plan_params[:amount].to_i)*100,
      :interval => plan_params[:interval],
      :nickname => plan_params[:name],
      :currency => 'usd',
      :trial_period_days => price ,
      :id => SecureRandom.uuid # This ensures that the plan is unique in stripe
    )
    @plan.stripe_response = subscription

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:amount, :name, :interval,:trial_period)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :plan_amount %>
  </div>
  
  <div class="field">
    <%= form.label :trial_period %>
    <%= form.number_field :trial_period, id: :plan_trial_period %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :plan_name %>
  </div>

  <div class="field">
    <%= form.label :interval %>
    <%#= form.select :interval, id: :plan_interval %>
    <%= form.select :interval,options_for_select([["Year",'year'],['Month','month']]), {multiple: false, :include_blank => false,prompt: "Please select Interval"},{id: :plan_interval} %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/_invoice.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Invoice</h4>
      </div>
      <div class="modal-body" id="invoice_modal_body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/plans/_invoice_data.html.erb
<!-- Simple Invoice - START -->
    <div class="row">
        <div class="col-xs-12">
            <div class="text-center">
                <h2>Invoice for Purchase #<%= invoice.number %></h2>
            </div>
            <hr>
        </div>
    </div>    
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class=""><strong>Amount:</strong> $<%= invoice.amount_due/100 %> </h3>
                            
                        </div>
                        <div class="col-md-6 text-right">
                            <h3 class=""><strong>Date:</strong> <%= Time.at(invoice.date).to_date%></h3>
                        </div>
                    </div>
                    
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <% invoice.lines["data"].each do |item| %>
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Item Description</strong></td>
                                    <td><strong>Period</strong></td>
                                    <td><strong>Item Price</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><%= item.description %></td>
                                    <td class=""><%= Time.at(item.period["start"]).to_date %> to <%= Time.at(item.period["end"]).to_date %></td>
                                    <td class=""><%= item.amount/100 %></td>
                                </tr>
                                <tr>
                                    <td class="highrow"></td>
                                    <td class="highrow"></td>
                                    <td class="highrow"><strong>Paid</strong></td>
                                    <td class="highrow text-right"><%= invoice.paid %></td>
                                </tr>
                                <tr>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow"><strong>Subtotal</strong></td>
                                    <td class="emptyrow text-right"><%= invoice.subtotal/100 %></td>
                                </tr>
                                <tr>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow"><strong>Total</strong></td>
                                    <td class="emptyrow text-right"><%= invoice.total/100 %></td>
                                </tr>
                            </tbody>
                        </table>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/plans/_modal.html.erb
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
          <%# @plans.each do |plan| %>
          <% if user_signed_in? %>
            <%#= @plans[1][:id] %>
            <% if @plans.present? %>
              <%= form_tag('/subscription_checkout', {method: :post}) do %>
                
                  <input name="stripe_plan_id" type="hidden" value="<%= @plans[1][:id] %>"></input>
                  <!--<input name="plan_id" type="hidden" value="<%#= plan[:id] %>"></input>-->
                  <script class="stripe-button" data-amount="<%= (@plans[1][:amount]) %>" data-currency="<%= @plans[1][:currency] %>" data-email="<%= @signed_in_user.email %>" data-image="/design360-logo.png" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" src="https://checkout.stripe.com/checkout.js"></script>
              <% end %>
            <% end %>
          <% end %>
          
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/plans/_modal_2.html.erb
  <!-- Modal -->
  <div class="modal fade" id="myModal_2" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal 2 Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
          
          <% if user_signed_in? and @plans.present? %>
          
            <%= form_tag('/subscription_checkout', {method: :post}) do %>
                <input name="stripe_plan_id" type="hidden" value="<%= @plans[0][:id] %>"></input>
                <!--<input name="plan_id" type="hidden" value="<%#= plan[:id] %>"></input>-->
                <script class="stripe-button" data-amount="<%= (@plans[0][:amount]) %>" data-currency="<%= @plans[0][:currency] %>" data-email="<%= @signed_in_user.email %>" data-image="/design360-logo.png" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" src="https://checkout.stripe.com/checkout.js"></script>
            <% end %>
          <% end %>
          
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table class="table">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Name</th>
      <th>Trial Period</th>
      <th>Interval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.amount %></td>
        <td><%= plan.name %></td>
        <td><%= plan.trial_period %></td>
        <td><%= plan.interval %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/invoices.html.erb
<div class="main-div">
   <div id="wrapper">
      <% user = current_employee || current_user %>
      <%= render partial: 'layouts/sidebar', locals:{notifications: user.notifications} %>
      <div class="table-responsive">
         <table class="table table-striped table-bordered table-hover dataTables-example managers" >
            <thead>
               <tr>
                  <th>Date</th>
                  <th>Invoice Number</th>
                  <th>Paid</th>
                  <th>Total</th>
               </tr>
            </thead>
            <tbody>
               <% @invoices["data"].each do |invoice| %>
               <tr>
                  <td><%= Time.at(invoice.date).to_datetime %></td>
                  <td><%= invoice.number %></td>
                  <td><%= invoice.paid %></td>
                  <td><%= invoice.total/100 %></td>
                  <td><%=  link_to "Show Invoice", show_invoice_path(stripe_invoice_id: invoice.id),{remote: true,class:"btn btn-info btn-xs","data-toggle":"modal","data-target":"#myModal"} %></td>
               </tr>
               <% end %>
            </tbody>
         </table>
      </div>
   </div>
</div>
<%= render 'invoice' %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @plan.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @plan.interval %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/plans/show_invoice.js.erb
$('#invoice_modal_body').html("<%= j (render partial: "invoice_data",locals: {invoice: @invoice}) %>");
$('#myModal').modal('show');