config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :plans
  mount Sidekiq::Web => '/sidekiq'
  devise_for :employees
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  mount ActionCable.server => '/cable'
  resources :employees, :except => [:index]
  get '/assign/employees', to: "employees#listing"
  resources :templates, :except => [:show, :index]
  resources :userhome, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :orders, :except => [:index]
  resources :attachments, :only => [:create]
  get '/admin/orders', to: 'home#admin_orders'
  get '/admin/managers', to: 'home#admin_managers'
  get '/admin/templates', to: 'home#admin_templates'
  get '/admin/clients', to: 'home#admin_clients'
  get '/managers/dashboard', to: 'home#manager_dashboard'
  get '/clients/dashboard', to: 'home#client_dashboard'
  get '/admin/dashboard', to: 'home#admin_dashboard'
  root 'home#index'
  get '/terms', to: 'home#terms'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/notifications', to: 'home#notifications'
  post 'subscription_checkout' => 'plans#subscription_checkout'
  get 'invoices' => 'plans#invoices'
  put 'cancel_subscription' => 'plans#cancel_subscription'
  get 'show_invoice' => 'plans#show_invoice'
  
  get 'unsub_user',to: 'home#unsub_user'
  post 'stripe_payment_succeeded' => 'plans#webhook_payment_succeeded'
  post 'stripe_payment_failure' => 'plans#webhook_payment_failure'
  # scope '/admin' do
    resources :chats, except: [:edit,:new]
    resources :messages
  # end
  match "*path", to: "home#error", via: :all
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Developed by <a href="http://www.systemplus.com.pk/" target="_blank">System Plus</a>
    </div>
    <div>
        <strong>Copyright</strong> Design360 &copy; 2018
    </div>
</div>
</div>
<% user = current_employee || current_user %>
<div id="iduser" data-user="<%= user.class.to_s+"_"+ user.id.to_s %>"></div>

app/views/layouts/_modal.html.erb
<script src="/devise.js"></script>
<script src="/inspinia.js"></script>
<div class="modal fade log"  id="social-modal-join" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
       
    <div class="modal-dialog">
    	<div class="loginmodal-container model-set">
    	    <div class="top-image">
    	        <img src="/model-logo.png" class="inner-image">
    	    </div>
  		<div class="loginmodal-container-2">
  			<h1>Start your free trial</h1>
        	<%= link_to 'Continue with Facebook',  "/users/auth/facebook" ,:class => "btn btn-lg btn-primary btn-fb" %>
			<%= link_to 'Continue with Google',  "/users/auth/google_oauth2" ,:class => "btn btn-lg btn-primary btn-google" %>
			<div class="row">
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-2">
					<p class="or">or</p>
				</div>
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
			</div>
			 <a class="btn btn-primary full-width m-b" id="modal-link-join" data-toggle="modal" data-target="#email-modal-join" data-dismiss="modal">Sign up with Email </a>
      
  			
  				<p style="text-align: center;">By signing up you agree to Design 360's</p>
  				<p style="text-align: center;"><a href="/terms">Terms and Conditions</a> and <a href="/privacy_policy">Privacy Policy</p>
  		</div>
  			<hr class="hr-or">
  			<p style="text-align: center;">Already have an account? <a href="#"  class="modal-link" data-toggle="modal" data-target="#social-modal-login" data-dismiss="modal"> Login </a></p>
  	</div> 
  </div>
</div>


<div class="modal fade log"  id="email-modal-join" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    	<div class="loginmodal-container model-set">
    	    <div class="top-image">
    	        <img src="/model-logo.png" class="inner-image">
    	    </div>
  		<div class="loginmodal-container-2">
  			<h1>Start your free trial</h1>
			 
            <%= form_for(:user, url: registration_path(:user), :class => "m-t") do |f| %>
                <div class="form-group">
                    <label class="log-label label-name">Name</label>
                    <%= f.text_field :name, autocomplete:"new-password", class:"form-control input-lg", id:"input-name", required: true, placeholder: "Name", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Name'" %>
                </div>
                <div class="form-group">
                    <label class="log-label label-email">Email</label>
                    <%= f.email_field :email, autocomplete:"new-password", class:"form-control input-lg", id:"input-email", required: true, placeholder: "Email", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Email'" %>
                </div>
                <div class="form-group">
                    <label class="log-label label-pass">Password</label>
                    <%= f.password_field :password, autocomplete:"new-password", class:"form-control input-lg", id:"input-pass",  required: true, placeholder: "Password", onfocus:"this.placeholder = ''",  onfocusout:"this.placeholder = 'Password'"%>
                </div>
                <div class="form-group">
                    <label class="log-label label-pass-c">Password Confirmation</label>
                    <%= f.password_field :password_confirmation, autocomplete:"new-password", class:"form-control input-lg", id:"input-pass-c",  required: true, placeholder: "Password Confirmation", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Password Confirmation'" %>
                </div>
                <%= f.submit "Submit", class:"btn full-width m-b btn-primary" %>
  			<% end %>
  			<div class="row">
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-2">
					<p class="or">or</p>
				</div>
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
			</div>
			 <a class="btn btn-primary full-width m-b" data-toggle="modal" data-target="#social-modal-join" data-dismiss="modal">Sign up with Social Media</a>
  				<p style="text-align: center;">By signing up you agree to Design 360's</p>
  				<p style="text-align: center;"><a href="/terms">Terms and Conditions</a> and <a href="/privacy_policy">Privacy Policy</p>
  		</div>
  			<hr class="hr-or">
  			<p style="text-align: center;">Already have an account? <a href="#"  class="modal-link" data-toggle="modal" data-target="#social-modal-login" data-dismiss="modal"> Login </a></p>
  	</div> 
  </div>
</div>


<div class="modal fade log"  id="social-modal-login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    	<div class="loginmodal-container model-set">
    	    <div class="top-image">
    	        <img src="/model-logo.png" class="inner-image">
    	    </div>
  		<div class="loginmodal-container-2">
  			<h1>Login to Design360</h1>
        	
	            <%= link_to 'Continue with Facebook',  "/users/auth/facebook" ,:class => "btn btn-lg btn-primary btn-fb" %>
	            <%= link_to 'Continue with Google',  "/users/auth/google_oauth2" ,:class => "btn btn-lg btn-primary btn-google" %>

			<div class="row">
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-2">
					<p class="or">or</p>
				</div>
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
			</div>
			 <a class="btn btn-primary full-width m-b" data-toggle="modal" data-target="#email-modal-login" data-dismiss="modal">Login with Email </a>
				
  		</div>
  			<hr class="hr-or">
  			<p style="text-align: center;">Don't have an account? <a href="#"  class="modal-link" data-toggle="modal" data-target="#social-modal-join" data-dismiss="modal"> SignUp </a></p>
  	</div> 
  </div>
</div>


<div class="modal fade log"  id="email-modal-login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    	<div class="loginmodal-container model-set">
    	    <div class="top-image">
    	        <img src="/model-logo.png" class="inner-image">
    	    </div>
  		<div class="loginmodal-container-2">
  			<h1>Login to Design360</h1>
			 
            <%= form_for(:user, url: session_path(:user), :class => "m-t") do |f| %>
                <div class="form-group">
                    <label class="log-label label-email">Email</label>
                    <%= f.email_field :email, autocomplete:"new-password", class:"form-control input-lg", id:"input-email", required: true, placeholder: "Email", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Email'" %>
                </div>
                <div class="form-group">
                    <label class="log-label label-pass">Password</label>
                    <%= f.password_field :password, autocomplete:"new-password", class:"form-control input-lg", id:"input-pass",  required: true, placeholder: "Password", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Password'" %>
                </div>
                <%= f.submit "Login", class:"btn full-width m-b btn-primary" %>
                
                <center>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              </a>
                <a href="/users/password/new"> Forgot Your Password?</a>
              </center>
  			<div class="row">
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-2">
					<p class="or">or</p>
				</div>
				<div class="col-md-5 col-sm-5 col-xs-5">
					<hr class="hr-or">
				</div>
			</div>
			 <a class="btn btn-primary full-width m-b" data-toggle="modal" data-target="#social-modal-login" data-dismiss="modal">Login with Social Media</a>
  		</div>
  			<hr class="hr-or">
  			<p style="text-align: center;">Don't have an account? <a href="#"  class="modal-link" data-toggle="modal" data-target="#social-modal-join" data-dismiss="modal"> Join </a></p>
  			<% end %>
  	</div> 
  </div>
</div>



<div class="modal fade log"  id="email-modal-employ" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    	<div class="loginmodal-container model-set">
    	    <div class="top-image">
    	        <img src="/model-logo.png" class="inner-image">
    	    </div>
  		<div class="loginmodal-container-2">
  			<h1>Login to Design360</h1>
			 
            <%= form_for(:employee, url: session_path(:employee), :class => "m-t") do |f| %>
                <div class="form-group">
                    <label class="log-label label-email">Email</label>
                    <%= f.email_field :email, autocomplete:"new-password", class:"form-control input-lg", id:"input-email", required: true, placeholder: "Email", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Email'" %>
                </div>
                <div class="form-group">
                    <label class="log-label label-pass">Password</label>
                    <%= f.password_field :password, autocomplete:"new-password", class:"form-control input-lg", id:"input-pass",  required: true, placeholder: "Password", onfocus:"this.placeholder = ''", onfocusout:"this.placeholder = 'Password'" %>
                </div>
                <%= f.submit "Login", class:"btn full-width m-b btn-primary" %>
                
                <center>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              </a>
                <a href="/employees/password/new"> Forgot Your Password?</a>
              </center>
  		
  		</div>
  			
  			<% end %>
  	</div> 
  </div>
</div>

<script>
	    $(document).ready(function() {
	    <% for id in 0..7 do %>
        $('.form-control').eq(<%=id%>).on('focus', function() {
            $('.log-label').eq(<%=id%>).addClass('label-after');
            $('.form-control').eq(<%=id%>).css('border-color', '#4771FA');
        });
        
        $('.form-control').on('focusout', function() {
            if ($('.form-control').eq(<%=id%>).val() == '') {
                $('.log-label').eq(<%=id%>).removeClass('label-after');
                $('.form-control').eq(<%=id%>).css('border-color', '#e5e6e7');

            } else if ($('.form-control').eq(<%=id%>).val() != '') {
                $('.log-label').eq(<%=id%>).addClass('label-after');
                $('.form-control').eq(<%=id%>).css('border-color', '#4771FA');
            }

        });
      <% end %>  
    });
        
	
</script>

app/views/layouts/_sidebar.html.erb
<style>
    .navbar-right{
        margin-right:0 !important;
    }
</style>

<script src="/inspinia.js" data-turbolinks-track="reload"></script>

<script src="/jquery_slim_scroll.js" data-turbolinks-track="reload"></script>
<script src="/metisMenu.js" data-turbolinks-track="reload"></script>
<!--<script src="/pace.min.js" data-turbolinks-track="reload"></script>--> <!--causing issues in turbolinks-->
<script src="/js_inspinia.js" data-turbolinks-track="reload"></script>
<% user = current_employee || current_user %>
<% notifications = user.notifications %>

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
    <% if current_user %>
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header text-center">
                <div class="dropdown profile-element"> 
                    <span>
                        <img alt="image" src="/design360-logo.png" width="100%" />
                    </span>
                    
                    <a style="cursor:default;"><span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><%= current_user.name %></strong>
                     </span> <span class="text-xs block">Dashboard</b></span> </span> </a>
                    
                </div>
                <div class="logo-element">
                    D
                </div>
            </li>
           <li class="<%= active_class(clients_dashboard_path) %>">
                <a href="<%= clients_dashboard_path %>"><i class="fas fa-tachometer-alt"></i> <span class="nav-label">Dashboard</span></a>
            </li>
            <li class="<%= active_class('/users/edit') %>">
                <a href="/users/edit"><i class="fas fa-cogs"></i> <span class="nav-label">Settings</span></a>
            </li>
            
            <li class="#">
                <a href="<%= notifications_path %>"><i class="fas fa-bullhorn"></i> <span class="nav-label">Notifications</span></a>
            </li>
            
            <li class="#">
                <a href="<%= chats_path %>"><i class="fas fa-inbox"></i> <span class="nav-label">Inbox(<span id="notification_count" data-count="<%= @unread_message_count %>"><%=@unread_message_count%>)</span></span></a>
            </li>
            
            
            <li class="#">
                <a href="<%= invoices_path %>"><i class="fa fa-money-bill-altuser"></i> <span class="nav-label"> Invoices </span></a>
            </li>
        </ul>
    <% end %>
    <% if current_employee %>
        <% if current_employee.role == "admin" %>
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header text-center">
                    <div class="dropdown profile-element"> 
                        <span>
                            <img alt="image" src="/design360-logo.png" width="100%" />
                        </span>
                        
                        <a style="cursor:default;"><span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><%= current_employee.name %></strong>
                         </span> <span class="text-xs block">Dashboard</b></span> </span> </a>
                        
                    </div>
                    <div class="logo-element">
                        D
                    </div>
                </li>
               <li class="<%= active_class(admin_dashboard_path) %>">
                    <a href="/admin/dashboard"><i class="fa fa-user"></i> <span class="nav-label">Dashboard</span></a>
                </li>
                <li class="<%= active_class(admin_templates_path) %>">
                    <a href="/admin/templates"><i class="fa fa-user"></i> <span class="nav-label">Templates</span></a>
                </li>
                <li class="<%= active_class(admin_orders_path) %>">
                    <a href="/admin/orders"><i class="fa fa-user"></i> <span class="nav-label">Orders</span></a>
                </li>
                <li class="<%= active_class(admin_managers_path) %>">
                    <a href="/admin/managers"><i class="fa fa-user"></i> <span class="nav-label">Managers</span></a>
                </li>
                <li class="<%= active_class(admin_clients_path) %>">
                    <a href="/admin/clients"><i class="fa fa-user"></i> <span class="nav-label">Clients</span></a>
                </li>
                <li class="<%= active_class(edit_employee_path(current_employee)) %>">
                    <a href="<%= edit_employee_path(current_employee) %>"><i class="fa fa-user"></i> <span class="nav-label">Settings</span></a>
                </li>
                
                <li class="#">
                    <a href="<%= notifications_path %>"><i class="fa fa-user"></i> <span class="nav-label">Notifications</span></a>
                </li>
                
                <li class="#">
                    <a href="<%= chats_path %>"><i class="fa fa-user"></i> <span class="nav-label">Inbox</span></a>
                </li>
            </ul>
        <% else %>
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header text-center">
                    <div class="dropdown profile-element"> 
                        <span>
                            <img alt="image" src="/design360-logo.png" width="100%" />
                        </span>
                        
                        <a style="cursor:default;"><span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><%= current_employee.name %></strong>
                         </span> <span class="text-xs block">Dashboard</b></span> </span> </a>
                        
                    </div>
                    <div class="logo-element">
                        D
                    </div>
                </li>
               <li class="<%= active_class(managers_dashboard_path) %>">
                    <a href="<%= managers_dashboard_path %>"><i class="fa fa-user"></i> <span class="nav-label">Dashboard</span></a>
                </li>
                <li class="<%= active_class(edit_employee_path(current_employee)) %>">
                    <a href="<%= edit_employee_path(current_employee) %>"><i class="fa fa-user"></i> <span class="nav-label">Settings</span></a>
                </li>
                
                <li class="#">
                    <a href="<%= notifications_path %>"><i class="fa fa-user"></i> <span class="nav-label">Notifications</span></a>
                </li>
                
                <li class="#">
                    <a href="<%= chats_path %>"><i class="fa fa-user"></i> <span class="nav-label">Inbox</span></a>
                </li>
            </ul>
        <% end %>
    <% end %>
    
    </div>
</nav>

<div id="page-wrapper" class="gray-bg">
    <div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary "><i class="fa fa-bars"></i> </a>
        <form role="search" class="navbar-form-custom" action="">
            <div class="form-group">
                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
            </div>
        </form>
    </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message"><a href="/">Design360</a></span>
            </li>
            <!--<li class="dropdown">-->
            <!--    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">-->
            <!--        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>-->
            <!--    </a>-->
            <!--    <ul class="dropdown-menu dropdown-messages">-->
                    
            <!--    </ul>-->
            <!--</li>-->
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell"></i>  <span class="label label-primary"><%= notifications.count %></span>
                </a>
                <ul class="dropdown-menu dropdown-alerts" id="notification_dropdown">
                    
                    <% if not notifications.blank? %>
                        <% notifications.limit(5).order('created_at DESC').each do |notification| %>
                            <%= render partial: 'notifications/notification', locals: {notification: notification} %>
                            <li class="divider"></li>
                        <% end %>
                    <% end %>
                    <!--<li>-->
                    <!--    <a href="#">-->
                    <!--        <div>-->
                    <!--            <i class="fa fa-twitter fa-fw"></i> You have 3 Orders Pending-->
                    <!--        </div>-->
                    <!--    </a>-->
                    <!--</li>-->
                </ul>
            </li>
            <!--<#% if current_user %>-->
            <!--    <li>-->
            <!--        <a href='/users/edit' >-->
            <!--            <i class="fa fa-sign-out"></i> Edit Profile-->
            <!--        </a>-->
            <!--    </li>-->
            <!--<#% elsif current_employee %>-->
            <!--    <li>-->
            <!--        <a href=<#%= edit_employee_path(current_employee) %>>-->
            <!--            <i class="fa fa-sign-out"></i> Edit Profile-->
            <!--        </a>-->
            <!--    </li>-->
            <!--<#% end %>-->
            <% if current_employee %>
                <li>
                    <a href="/employees/sign_out" data-method="delete">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            <% elsif current_user %>
                <li>
                    <a href="/users/sign_out" data-method="delete">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            <% end %>
            
        </ul>

    </nav>
    </div>

app/views/layouts/_statistics.html.erb
    <div class="container">
        <div class="row">
            
            <div class="col-md-12">
                <div class="row wrapper border-bottom white-bg page-heading mb-lg" id="Orders">
                 <div class="col-lg-12">
                    <h2>Users</h2>
                 </div>
                </div>
                <section class="blocks">
                    <div class="row">
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Clients</p>
                                        <h3><%= User.count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Managers</p>
                                        <h3><%= Employee.where(role:1).count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                   </div>
                </section>
                <div class="row">
                <div class="row wrapper border-bottom white-bg page-heading mb-lg" id="Orders">
                     <div class="col-lg-12">
                        <h2>Orders</h2>
                     </div>
                </div>
                </div>
                <section class="blocks">
                    <div class="row">
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Pending</p>
                                        <h3><%= Order.where(status: "pending").count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Assigned</p>
                                        <h3><%= Order.where(status: "assigned").count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Delivered</p>
                                        <h3><%= Order.where(status: "delivered").count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>In Revision</p>
                                        <h3><%= Order.where(status: "in_revision").count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Completed</p>
                                        <h3><%= Order.where(status: "complete").count %></h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                   </div>
                </section>
                <div class="row">
                    <div class="row wrapper border-bottom white-bg page-heading mb-lg" id="Orders">
                     <div class="col-lg-12">
                        <h2>Subscriptions</h2>
                     </div>
                  </div>
                </div>
                <section class="blocks">
                    <div class="row">
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Basic Trial</p>
                                        <h3>10</h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Basic Active</p>
                                        <h3>10</h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Basic Cancelled</p>
                                        <h3>10</h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Premium Trial</p>
                                        <h3>10</h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                   </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Premium Active</p>
                                        <h3>10</h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-6 col-sm-3" style="margin-bottom:80px;">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <center>
                                        <p>Premium Cancelled</p>
                                        <h3>10</h3>
                                    </center>
                                </div>
                            </div>
                        </div>
                        
                   </div>
                </section>
            </div>
        </div>
    </div>